server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    prefix:  @thymeleaf.template.folder@
  resources:
    static-locations:  @spring.resources.static.locations@
    cache-period: 0
  jpa:
    hibernate:
      ddl-auto: update